services:
  - type: web
    name: blazor-weather-app
    env: docker
    branch: main
    buildCommand: dotnet publish BlazorWeatherApp/BlazorWeatherApp.csproj -c Release -o out
    startCommand: dotnet out/BlazorWeatherApp.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT